#!/bin/bash

if [ $EUID -eq 0 ]; then
    SETUSER="sudo -u postgres"
elif [ $USER == 'postgres' ]; then
    SETUSER=
else
    echo "This script must be run as root or as postgres"
    exit 1
fi

echo "CREATE USER test WITH SUPERUSER PASSWORD 'test'; CREATE DATABASE test WITH OWNER test;" | ${SETUSER} psql
echo "ALTER USER test WITH SUPERUSER;" | ${SETUSER} psql
echo "CREATE USER sonar WITH PASSWORD 'sonar'; GRANT ALL PRIVILEGES ON DATABASE test TO sonar;" | ${SETUSER} psql
echo "CREATE EXTENSION IF NOT EXISTS sonar_fdw; GRANT ALL ON FOREIGN DATA WRAPPER sonar_fdw TO test;" | ${SETUSER} psql -U postgres test

cd '/opt/sonar-fdw/SonarSQLSync'
${SETUSER} python setup_fdw.py
